vich_uploader:
    db_driver: orm
    metadata:
        #auto_detection: false
        #cache: file
        #type: attribute    # or annotation
        #type: annotation    # or annotation

    mappings:
        nodes:
            uri_prefix: /img/node
            upload_destination: '%kernel.project_dir%/public/img/node'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
