vich_uploader:
    db_driver: orm
    metadata:
        #auto_detection: false
        #cache: file
        #type: attribute    # or annotation
        #type: annotation    # or annotation

    mappings:
        nodes:
            uri_prefix: /files/node
            upload_destination: '%kernel.project_dir%/public/files/node'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        others:
            uri_prefix: /files/others
            upload_destination: '%kernel.project_dir%/public/files/others'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        media_object:
            uri_prefix: /files/media
            upload_destination: '%kernel.project_dir%/public/files/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
